// Curric config — populated at build time via Vercel env vars
// Do NOT edit this file directly. Edit config.template.js instead.
(function () {
  window.__CURRIC_CONFIG__ = {
    supabaseUrl: 'https://hvynpslokgslpmekqwmg.supabase.co',
    supabaseKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2eW5wc2xva2dzbHBtZWtxd21nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg3NjQwMjgsImV4cCI6MjA5NDM0MDAyOH0.ZlwsneuKHDEeYHNktEqq15Sk-iZt-vQsOeGMHXggbK0',
    stripePrice: 199,
    priceLabel: '$1.99',
    maxBetaSpots: 15,
  };
})();
